# Generated by Django 4.2.16 on 2024-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('aboutText', models.TextField()),
                ('CampusRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('AthleticsRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('SafteyRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('SocialRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ProffesorRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('DormRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('DiningRating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('GraduationRate', models.DecimalField(decimal_places=1, max_digits=4)),
                ('TotalUndergradStudents', models.IntegerField()),
                ('TotalGradStudents', models.IntegerField()),
            ],
        ),
    ]
