# Generated by Django 4.2.16 on 2024-11-08 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0002_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='AthleticsRating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='CampusRating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='DiningRating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='DormRating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='GraduationRate',
        ),
        migrations.RemoveField(
            model_name='university',
            name='ProffesorRating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='SafteyRating',
        ),
        migrations.RemoveField(
            model_name='university',
            name='SocialRating',
        ),
        migrations.CreateModel(
            name='UniversityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('campus', 'Campus'), ('athletics', 'Athletics'), ('safety', 'Safety'), ('social', 'Social'), ('professor', 'Professor'), ('dorm', 'Dorm'), ('dining', 'Dining')], max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='MajorHelp.university')),
            ],
        ),
    ]
