# Generated by Django 4.2.16 on 2024-11-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0003_remove_university_athleticsrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='GraduationRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
