# Generated by Django 4.2.16 on 2024-11-12 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0004_university_graduationrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityrating',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
