# Generated by Django 5.1.3 on 2024-11-13 03:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0005_alter_universityrating_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityrating',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Check if the university is public; leave unchecked for private'),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('in_state_tuition', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('out_of_state_tuition', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='MajorHelp.university')),
            ],
            options={
                'verbose_name': 'Major',
                'verbose_name_plural': 'Majors',
            },
        ),
    ]
