# Generated by Django 5.1.3 on 2024-11-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0006_alter_universityrating_options_university_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='department',
            field=models.CharField(choices=[('Humanities and Social Sciences', 'Humanities and Social Sciences'), ('Natural Sciences and Mathematics', 'Natural Sciences and Mathematics'), ('Business and Economics', 'Business and Economics'), ('Education', 'Education'), ('Engineering and Technology', 'Engineering and Technology'), ('Health Sciences', 'Health Sciences'), ('Arts and Design', 'Arts and Design'), ('Agriculture and Environmental Studies', 'Agriculture and Environmental Studies'), ('Communication and Media', 'Communication and Media'), ('Law and Criminal Justice', 'Law and Criminal Justice')], max_length=50),
        ),
    ]
