# Generated by Django 5.1.3 on 2024-11-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0007_alter_major_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={},
        ),
        migrations.AlterModelOptions(
            name='universityrating',
            options={},
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
