# Generated by Django 5.1.3 on 2024-11-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0007_review_university'),
        ('MajorHelp', '0008_alter_major_options_alter_universityrating_options_and_more'),
    ]

    operations = [
    ]
