# Generated by Django 5.1.3 on 2025-11-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0007_alter_customuser_savedcalcs_delete_chatmessage'),
        ('MajorHelp', '0008_auto_20251118_2341'),
    ]

    operations = [
    ]
