# Generated by Django 5.1.3 on 2025-11-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0009_merge_20251118_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
