# Generated by Django 5.1.3 on 2024-11-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0009_merge_20241113_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.TextField(),
        ),
    ]
