# Generated by Django 4.2.16 on 2024-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0010_alter_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
