# Generated by Django 5.1.3 on 2025-11-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0010_alter_university_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
