# Generated by Django 4.2.16 on 2024-11-14 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MajorHelp', '0012_alter_university_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityrating',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='university_ratings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='universityrating',
            unique_together={('university', 'category', 'user')},
        ),
    ]
