# Generated by Django 5.1.3 on 2024-11-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0013_universityrating_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
