# Generated by Django 5.1.3 on 2025-03-08 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0014_alter_universityreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaid',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MajorHelp.university'),
        ),
    ]
