# Generated by Django 5.1.3 on 2024-11-15 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0015_alter_university_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='in_state_tuition',
        ),
        migrations.RemoveField(
            model_name='major',
            name='out_of_state_tuition',
        ),
        migrations.AddField(
            model_name='major',
            name='in_state_max_tuition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='major',
            name='in_state_min_tuition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='major',
            name='out_of_state_max_tuition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='major',
            name='out_of_state_min_tuition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
