# Generated by Django 5.1.3 on 2025-03-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0015_financialaid_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaid',
            name='university',
        ),
    ]
