# Generated by Django 5.1.3 on 2024-11-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0016_remove_major_in_state_tuition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
