# Generated by Django 5.1.3 on 2024-11-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0017_major_slug_alter_major_major_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='major_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=255),
        ),
    ]
