# Generated by Django 5.1.3 on 2025-03-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0017_university_applicableaids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='applicableAids',
        ),
    ]
