# Generated by Django 5.1.3 on 2025-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0018_remove_university_applicableaids'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='applicableAids',
            field=models.JSONField(default=dict),
        ),
    ]
