# Generated by Django 5.1.3 on 2024-11-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0018_major_major_description_alter_major_major_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
