# Generated by Django 5.1.3 on 2025-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0019_university_applicableaids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='applicableAids',
        ),
        migrations.AddField(
            model_name='university',
            name='applicableAids',
            field=models.ManyToManyField(blank=True, related_name='university', to='MajorHelp.financialaid'),
        ),
    ]
