# Generated by Django 5.1.3 on 2024-11-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0019_alter_university_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('review_text', models.TextField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major_reviews', to='MajorHelp.major')),
            ],
        ),
    ]
