# Generated by Django 5.1.3 on 2025-03-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0020_remove_university_applicableaids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='savedCalcs',
            field=models.JSONField(default=dict),
        ),
    ]
