# Generated by Django 5.1.3 on 2024-11-26 03:12

import MajorHelp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0020_majorreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorreview',
            name='username',
        ),
        migrations.AddField(
            model_name='majorreview',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MajorHelp.university'),
        ),
        migrations.AddField(
            model_name='majorreview',
            name='user',
            field=models.ForeignKey(default=MajorHelp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
