# Generated by Django 5.1.7 on 2025-03-29 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0021_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MajorHelp.major'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MajorHelp.university'),
        ),
    ]
