# Generated by Django 4.2.16 on 2024-11-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0021_remove_majorreview_username_majorreview_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('review_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university_review', to='MajorHelp.university')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
