# Generated by Django 5.1.3 on 2025-04-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0021_discussioncategory_discussionthread_threadreply'),
        ('MajorHelp', '0022_favorite_major_alter_favorite_university'),
    ]

    operations = [
    ]
