# Generated by Django 4.2.16 on 2025-04-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0022_favorite_major_alter_favorite_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='PrimaryColor',
            field=models.CharField(default='#268f95', max_length=7),
        ),
    ]
