# Generated by Django 5.1.3 on 2025-04-03 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0021_customuser_savedcalcs'),
        ('MajorHelp', '0022_favorite_major_alter_favorite_university'),
    ]

    operations = [
    ]
