# Generated by Django 4.2.16 on 2025-04-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0023_university_primarycolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='PrimaryColor',
            new_name='primary_color',
        ),
    ]
