# Generated by Django 4.2.16 on 2025-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0024_rename_primarycolor_university_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='secondary_color',
            field=models.CharField(default='#268f95', max_length=7),
        ),
    ]
