# Generated by Django 4.2.16 on 2025-04-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0025_university_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='secondary_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
