# Generated by Django 5.1.3 on 2025-04-04 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0023_merge_20250402_2145'),
        ('MajorHelp', '0026_alter_university_secondary_color'),
    ]

    operations = [
    ]
