# Generated by Django 5.1.3 on 2025-04-04 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MajorHelp', '0023_merge_20250403_0421'),
        ('MajorHelp', '0027_merge_20250403_1907'),
    ]

    operations = [
    ]
