# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestsubmitUniversityRequest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testsubmitUniversityRequest(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(3824, 2012)
    self.driver.find_element(By.LINK_TEXT, "Search").click()
    self.driver.find_element(By.ID, "filter-dropdown").click()
    dropdown = self.driver.find_element(By.ID, "filter-dropdown")
    dropdown.find_element(By.XPATH, "//option[. = 'School']").click()
    self.driver.find_element(By.ID, "school-option").click()
    self.driver.find_element(By.ID, "search-query").click()
    self.driver.find_element(By.ID, "search-query").send_keys("DoesNotExistU")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.LINK_TEXT, "Request University").click()
    self.driver.find_element(By.ID, "request_text").click()
    self.driver.find_element(By.ID, "request_text").send_keys("DoesNotExistU")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
